/*
EMAIL
  CREATE USER, SEND ACTIVATION TOKEN
  USER, RESEND ACTIVATION TOKEN
  USER, ACTIVATE USER ACCOUNT
  USER, FORGET PASSWORD
  ORDER, SEND ORDER
  ORDER CANCEL, SEND CANCEL ORDER
  
CUSTOMER
  USER, ALTER PASSWORD
  */
